# An unique identifier for the head node and workers of this cluster.
cluster_name: rayllm

# Cloud-provider specific configuration.
provider:
    type: local
    head_ip: 127.0.0.1
    # You may need to supply a public ip for the head node if you need
    # to run `ray up` from outside of the Ray cluster's network
    # (e.g. the cluster is in an AWS VPC and you're starting ray from your laptop)
    # This is useful when debugging the local node provider with cloud VMs.
    # external_head_ip: YOUR_HEAD_PUBLIC_IP
    worker_ips: [10.233.1.1]

auth:
    ssh_user: xiayao
# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 2
